# Generated by Django 5.2.8 on 2025-12-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='surname',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='surname',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
